values:
  5: 0,1,2,3,4,5,6
  6: 0,1,2,3
  8: 0,1,2,3,4,5,6,7
  9: 0,1,2,3,4,5,6,7
  10: 0,1,2,3,4,5,6,7
  11: 0,1,2,3,4,5,6,7
  17: 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
  18: 4,5,6,7,14,15
  20: 0,1,2
  23: 0,1,2,3,4,5
  24: 0,1,2,3,4,5,6
  26: 0,1,2,3,8,9,10,11
  27: 0,1,2,3,4,5
  28: 0,1,2,3,4,5
  29: 0,1,2,3,4,5,8,9,10,11,12
  30: 0,1,2
  31: 0,1,2,3
  33: 0,1,2,3,4,5,8,9,10,11,12  
  35: 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
  39: 0,1
  43: 0,1,2,3,4,5,6,7,8,9,10,11,12,13
  44: 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
  49: 0,1
  50: 1,2,3,4,5
  59: 0,1,2,3,4,5,6,7
  60: 0,7
  61: 0,1,2,3
  62: 0,1,2,3
  63: 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
  64: 0,1,2,3,4,5,6,7,8
  65: 0,1,2,3
  66: 0,1,2,3,4,5,6,7,8,9
  67: 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
  69: 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
  70: 0,1,2,3,4,5,6,7,8
  75: 1,2,3,4,5
  77: 1,2,3,4
  76: 1,2,3,4,5
  78: 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
  79: 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
  85: 0,1,2,3
  86: 0,1,2,3,4,5,6,7,8,9,10,11,12,13
  89: 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
  91: 0,1,2,3,4,5,6,7,8,9,10,11,12,13
  92: 0,1,2,3,4,5,6
  93: 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
  96: 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
  97: 0,1,2,3,4,5,6,7
  98: 0,1,2,3,4,5,6,7,8,9,10,11,12
  99: 0,1,2,3,4,5,6,7,8,9,10,14,15
  100: 0,1,2,3,4,5,6,7,8,9,10,14,15
  101: 0,1
  102: 0,1
  104: 0,1,2,3,4,5,6,7
  105: 0,1,2,3,4,5,6,7
  106: 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
  108: 0,1,2,3,4,5,6,7
  109: 0,1,2,3,4,5,6,7
  113: 0,1,2
  114: 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
  115: 0,1,2,3
  117: 0,1,2,3,4,5,6,7
  118: 0,1,2,3
  120: 0,1,2,3,4,5,6,7
  122: 0,1,2
  125: 0,1,2,3,4,5,6,7,8,9
  126: 0,1,2,3,8,9,10,11
  127: 0,1,2,3,4,5,6,7,8,9,10,11
  128: 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
  130: 1,2,3,4
  131: 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
  134: 0,1,2,3,4,5,6,7
  135: 0,1,2,3,4,5,6,7
  136: 0,1,2,3,4,5,6,7
  139: 0,1,2,3,4,5,6
  140: 0,1,2,3,4,5,6,7,8,9,10,11
  141: 0,1,2,3,4,5,6,7
  142: 0,1,2,3,4,5,6,7
  145: 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
  154: 0,1,2,3,4
  155: 0,1,2,3,4,5,6,7,8,9
  157: 0,1,2,3,4,5
  158: 0,1,2,3,4,5
  159: 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
  170: 0,4,8
  171: 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
names:
  5:
    0: "Oak Planks"
    1: "Pine Planks"
    2: "Birch Planks"
    3: "Jungle Planks"
    4: "Wide Light Planks"
    5: "Reinforced Planks"
    6: "Wooden Crate"
  6:
    0: "Oak Sapling"
    1: "Pine Sapling"
    2: "Birch Sapling"
    3: "Jungle Sapling"
    4: "Oak Sapling"
    5: "Pine Sapling"
    6: "Birch Sapling"
    7: "Jungle Sapling"
    8: "Oak Sapling"
    9: "Pine Sapling"
    10: "Birch Sapling"
    11: "Jungle Sapling"
    12: "Oak Sapling"
    13: "Pine Sapling"
    14: "Birch Sapling"
    15: "Jungle Sapling"
  17:
    0: "Oak Log (Vertical)"
    1: "Pine Log (Vertical)"
    2: "Birch Log (Vertical)"
    3: "Jungle Log (Vertical)"
    4: "Oak Log (East-West)"
    5: "Pine Log (East-West)"
    6: "Birch Log (East-West)"
    7: "Jungle Log (East-West)"
    8: "Oak Log (North-South)"
    9: "Pine Log (North-South)"
    10: "Birch Log (North-South)"
    11: "Jungle Log (North-South)"
    12: "Oak Log (Directionless)"
    13: "Pine Log (Directionless)"
    14: "Birch Log (Directionless)"
    15: "Jungle Log (Directionless)"
  18:
    0: "Oak Leaves"
    1: "Pine Needles"
    2: "Birch Leaves"
    3: "Jungle Leaves"
    4: "Oak Leaves"
    5: "Pine Needles"
    6: "Birch Leaves"
    7: "Jungle Leaves"
    8: "Oak Leaves"
    9: "Pine Needles"
    10: "Birch Leaves"
    11: "Jungle Leaves"
    12: "Oak Leaves"
    13: "Pine Needles"
    14: "Dark Birch Leaves"
    15: "Cherry Blossoms"
  19:
    0: "Wicker"
  20:
    0: "Glass"
    1: "Connected Glass"
    2: "Invisible Glass"
  24:
    0: "Sandstone"
    1: "Sandstone Column (Vertical)"
    2: "Sandstone Accent"
    3: "Sandstone Column (Horizontal)"
    4: "Sandstone Edging"
    5: "Pink Sandstone"
    6: "Orange Sandstone"
  30:
    0: "Spider Web"
    1: "Swirly Steam"
    2: "Spotty Steam"
  31:
    2: "Cattails"
  39:
    0: "Brown Mushroom"
    1: "Blue Mushroom"
  43:
    0: "Stone Double Step"
    1: "Sandstone Double Step"
    2: "Wood Double Step"
    3: "Cobblestone Double Step"
    4: "Brick Double Step"
    5: "Stone Brick Double Step"
    6: "Nether Brick Double Step"
    7: "Quartz Double Step"
    8: "Stone Accent"
    9: "Metal Panel (Gold)"
    10: "Metal Panel (Iron)"
    11: "Copper Panel"
    12: "Bronze"
    13: "Bronze Panel"
    14: "Nether Brick Double Step"
    15: "Quartz Double Step"
  49:
    1: "Pure Darkness"
  67:
    8: "Stone Stairs"
    9: "Stone Stairs"
    10: "Stone Stairs"
    11: "Stone Stairs"
    12: "Stone Stairs"
    13: "Stone Stairs"
    14: "Stone Stairs"
    15: "Stone Stairs"
  79:
    0: "Ice"
    1: "Red Ice"
    2: "Orange Ice"
    3: "Peach Ice"
    4: "Yellow Ice"
    5: "Green Ice"
    6: "Seafoam Ice"
    7: "Teal Ice"
    8: "Cyan Ice"
    9: "Blue Ice"
    10: "Purple Ice"
    11: "Violet Ice"
    12: "Pink Ice"
    13: "Magenta Ice"
    14: "Black Ice"
    15: "White Ice"
  85:
    0: "Oak Fence"
    1: "Pine Fence"
    2: "Birch Fence"
    3: "Jungle Fence"
  86:
    0: "Pumpkin"
    1: "Pumpkin"
    2: "Pumpkin"
    3: "Pumpkin"
    4: "White Monitor"
    5: "White Monitor"
    6: "White Monitor"
    7: "White Monitor"
    8: "White Monitor"
    9: "Black Monitor"
    10: "Black Monitor"
    11: "Black Monitor"
    12: "Black Monitor"
    13: "Black Monitor"
    14: "Pumpkin"
    15: "Pumpkin"
  89:
    0: "Glowstone"
    1: "Red Glowstone"
    2: "Orange Glowstone"
    3: "Peach Glowstone"
    4: "White Glowstone"
    5: "Green Glowstone"
    6: "Seafoam Glowstone"
    7: "Teal Glowstone"
    8: "Cyan Glowstone"
    9: "Blue Glowstone"
    10: "Purple Glowstone"
    11: "Violet Glowstone"
    12: "Pink Glowstone"
    13: "Magenta Glowstone"
    14: "Black Glowstone"
    15: "Invisible Glowstone"
  91:
    0: "Jack O Lantern"
    1: "Jack O Lantern"
    2: "Jack O Lantern"
    3: "Jack O Lantern"
    4: "White Monitor (On)"
    5: "White Monitor (On)"
    6: "White Monitor (On)"
    7: "White Monitor (On)"
    8: "White Monitor (On)"
    9: "Black Monitor (On)"
    10: "Black Monitor (On)"
    11: "Black Monitor (On)"
    12: "Black Monitor (On)"
    13: "Black Monitor (On)"
    14: "Jack O Lantern"
    15: "Jack O Lantern"
  97:
    0: "Stone"
    1: "Cobblestone"
    2: "Stone Brick"
    3: "Dark Cobble"
    4: "Light Cobble"
    5: "Dark Stone"
    6: "Wet Stone"
    7: "Light Stone"
  98:
    0: "Stone Brick"
    1: "Mossy Stone Brick"
    2: "Cracked Stone Brick"
    3: "Accent Brick"
    4: "Stone Column (Horizontal)"
    5: "Stone Column (Vertical)"
    6: "Brown Brick"
    7: "Sandstone Brick"
    8: "River Brick"
    9: "Dungeon Brick"
    10: "White Brick"
    11: "Shingles"
    12: "Colourful Brick"
  101:
    0: "Metal Fence"
    1: "Copper Fence"
  102:
    0: "Thin Glass"
    1: "Connected Texture Thin Glass"
  113:
    1: "Light Metal Fence"
    2: "Dark Metal Fence"
  114:
    8: "Metal Stairs"
    9: "Metal Stairs"
    10: "Metal Stairs"
    11: "Metal Stairs"
    12: "Metal Stairs"
    13: "Metal Stairs"
    14: "Metal Stairs"
    15: "Metal Stairs"
  115:
    0: "Blue Berries"
    1: "Yellow Berries"
    2: "Yellow Berries"
    3: "Red Berries"
  122:
    0: "Dragon Egg"
    1: "Metal Egg"
    2: "Crystal Egg"
  125:
    0: "Oak Double Step"
    1: "Pine Double Step"
    2: "Birch Double Step"
    3: "Jungle Double Step"
    4: "Light Metal Beam (Horizontal)"
    5: "Light Metal Beam (Vertical)"
    6: "Metal Beam (Horizontal)"
    7: "Metal Beam (Vertical)"
    8: "Dark Metal Beam (Horizontal)"
    9: "Dark Metal Beam (Vertical)"
  126:
    0: "Oak Step"
    1: "Pine Step"
    2: "Birch Step"
    3: "Jungle Step"
    4: "Oak Step"
    5: "Pine Step"
    6: "Birch Step"
    7: "Jungle Step"
    8: "Oak Step"
    9: "Pine Step"
    10: "Birch Step"
    11: "Jungle Step"
    12: "Oak Step"
    13: "Pine Step"
    14: "Birch Step"
    15: "Jungle Step"
  128:
    8: "Invisible Stairs"
    9: "Invisible Stairs"
    10: "Invisible Stairs"
    11: "Invisible Stairs"
    12: "Invisible Stairs"
    13: "Invisible Stairs"
    14: "Invisible Stairs"
    15: "Invisible Stairs"
  130:
    0: "Ender Chest"
    1: "Ender Chest"
    2: "Ender Chest"
    3: "Ender Chest"
    4: "Ender Chest"
    5: "Ender Chest"
    6: "Ender Chest"
    7: "Ender Chest"
    8: "Ender Chest"
    9: "Ender Chest"
    10: "Ender Chest"
    11: "Ender Chest"
    12: "Ender Chest"
    13: "Ender Chest"
    14: "Ender Chest"
    15: "Ender Chest"
  139:
    0: "Cobble Wall"
    1: "Mossy Cobble Wall"
    2: "Sandstone Wall"
    3: "Stone Wall"
    4: "Stone Brick Wall"
    5: "Quartz Wall"
    6: "Light Cobble Wall"
  155:
    0: "Quartz"
    1: "Quartz Pattern"
    2: "Quartz Column (Vertical)"
    3: "Quartz Column (North-South)"
    4: "Quartz Column (East-West)"
    5: "Green Marble"
    6: "Pink Marble"
    7: "Quartz Column (Vertical)"
    8: "Quartz Column (Horizontal)"
    9: "Quartz Accent"
